# Generated by Django 3.0.5 on 2020-11-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctNumber', models.CharField(max_length=11, verbose_name='Имя контакта')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя контакта')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия контакта')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('numbers', models.ManyToManyField(blank=True, related_name='contacts_number', to='api.Number', verbose_name='Номера контакта')),
            ],
        ),
    ]
