# Generated by Django 3.0.5 on 2020-11-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='numbers',
            field=models.ManyToManyField(blank=True, related_name='contact_numbers', to='api.Number', verbose_name='Номера контакта'),
        ),
    ]
