# Generated by Django 3.0.5 on 2020-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201121_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='numbers',
            field=models.ManyToManyField(related_name='contact_numbers', to='api.Number', verbose_name='Номера контакта'),
        ),
        migrations.AlterField(
            model_name='number',
            name='correctNumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Имя контакта'),
        ),
    ]
