# Generated by Django 3.0.5 on 2020-11-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201121_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='birthdate',
            new_name='birthday',
        ),
        migrations.AlterField(
            model_name='number',
            name='correctNumber',
            field=models.CharField(max_length=11, null=True, verbose_name='Корректный номер'),
        ),
    ]
