# Generated by Django 3.0.5 on 2020-11-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201121_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='category',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='number',
            name='correctNumber',
            field=models.CharField(max_length=11, verbose_name='Корректный номер'),
        ),
    ]
