# Generated by Django 3.0.5 on 2020-11-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201122_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='correctNumber',
            field=models.CharField(max_length=12, verbose_name='Корректный номер'),
        ),
    ]
