# Generated by Django 3.0.5 on 2020-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201122_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='category',
            field=models.CharField(default='Отсутствует', max_length=150, verbose_name='Категория'),
        ),
    ]
