# Generated by Django 3.0.5 on 2020-11-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201122_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, default='Отсутствует', null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='number',
            name='category',
            field=models.CharField(blank=True, default='Отсутствует', max_length=150, null=True, verbose_name='Категория'),
        ),
    ]
